version: "3.8"

services:
  db:
    image: postgres:13.4
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eko
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./backend/src/main/resources/only_schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./backend/src/main/resources/schema_postgres.sql:/docker-entrypoint-initdb.d/2.sql


#  db:
#    image: mysql:latest
#    container_name: mysql-db
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      - MYSQL_ROOT_PASSWORD=eko
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./backend/src/main/resources/only_schema.sql:/docker-entrypoint-initdb.d/1.sql
#      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/2.sql

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://backend:8080
    ports:
      - "5000:5000"
    depends_on:
      - backend